version: "3.8"

services:
  reverse:
version: "3.8"

services:
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
      - 81:80

  nginx:
    depends_on:
      - reverse
    image: nginx:alpine
    restart: always

  www:
    depends_on:
    - db
    - reverse
    image: php:7.4.18-apache
    volumes:
    - ".html/:/var/www/html/"
    ports:
    - 80:80

  db:
     image: mysql:5.7
     restart: always
     volumes:
      - "./mysql:/var/lib/mysql:rw"
     env_file:
      - conf.env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
        - db:db
    ports:
        - 8080:80
    env_file: 
      - conf.env

  wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - 8000:80
     restart: always
     volumes: ['.wordpress/:/var/www/html']
     env_file:
       - conf.env
