version: "3.3"

services:
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
      - 81:80

  nginx:
    depends_on:
      - reverse
    image: nginx:alpine
    restart: always

  www:
    depends_on:
    - db
    - reverse
    image: php:7.4.18-apache
    ports:
    - 80:80

  db:
     image: mysql:5.7
     restart: always
     env_file: conf.env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
        - db:db
    ports:
        - 8080:80
    env_file: conf.env

  wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - 8000:80
     restart: always
     environment:
       WORDPRESS_DB_HOST: db
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress